name: iris_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  fluttertoast: ^8.2.8
  cloud_firestore: ^4.17.5
  shared_preferences: ^2.2.2
  camera: ^0.11.1
  path_provider: ^2.0.15
  path: ^1.8.3
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  http: ^1.2.1 # Untuk membuat permintaan HTTP
  image: ^4.1.7     # Or the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
     
flutter:
  assets:
    - assets/images/
  uses-material-design: true