name: iris_application
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  fluttertoast: ^8.2.10
  shared_preferences: ^2.3.3
  image_picker: ^1.0.4
  http: ^1.1.0
  image: ^4.1.7
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  google_mlkit_commons: ^0.7.1
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_face_detection: ^0.10.0
  google_mlkit_barcode_scanning: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
     
flutter:
  assets:
    - assets/images/
  uses-material-design: true