// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZFj6PvmxmdBkvJo0Q69CVkvSST64voE',
    appId: '1:618479568238:web:316ce1e7a71732f5586d7f',
    messagingSenderId: '618479568238',
    projectId: 'iris-85abc',
    authDomain: 'iris-85abc.firebaseapp.com',
    storageBucket: 'iris-85abc.firebasestorage.app',
    measurementId: 'G-M9E944P1CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC3laZwO2XTFQEWEzQ9iajQ03llwOnS_Y',
    appId: '1:618479568238:android:c1cebc90411cf4c8586d7f',
    messagingSenderId: '618479568238',
    projectId: 'iris-85abc',
    storageBucket: 'iris-85abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA70rKppD-M75Q0z5xJ7cb3rDi63W8JqTI',
    appId: '1:618479568238:ios:1751e18838a80459586d7f',
    messagingSenderId: '618479568238',
    projectId: 'iris-85abc',
    storageBucket: 'iris-85abc.firebasestorage.app',
    iosBundleId: 'com.example.irisApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA70rKppD-M75Q0z5xJ7cb3rDi63W8JqTI',
    appId: '1:618479568238:ios:1751e18838a80459586d7f',
    messagingSenderId: '618479568238',
    projectId: 'iris-85abc',
    storageBucket: 'iris-85abc.firebasestorage.app',
    iosBundleId: 'com.example.irisApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUZFj6PvmxmdBkvJo0Q69CVkvSST64voE',
    appId: '1:618479568238:web:a458ff4af58fd52b586d7f',
    messagingSenderId: '618479568238',
    projectId: 'iris-85abc',
    authDomain: 'iris-85abc.firebaseapp.com',
    storageBucket: 'iris-85abc.firebasestorage.app',
    measurementId: 'G-9NSNLPEKBF',
  );
}
